version: "2"

services:
 minetest:
  image: registry.rudin.io/x86/minetest:backport-0.4
  restart: always
  depends_on:
   - "postgres"
  volumes:
   - "./minetest:/data"
   - "./world.mt:/data/world/world.mt:ro"
   - "../tileserver_mod:/data/world/worldmods/tileserver_mod"
  command: minetestserver --config /data/minetest.conf --world /data/world/
  ports:
   - "30000:30000/udp"

 postgres:
  image: postgres
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"

